FROM python:3.9.18-slim-bullseye

WORKDIR /code

COPY requirements.txt /code/

RUN pip3 install -r requirements.txt

COPY . .

CMD ["celery", "-A", "backend.celery", "worker", "--pool=solo", "-l", "INFO"]