version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    volumes:
      - ./data/db:/app/db

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery_worker
    depends_on:
      - redis
    volumes:
      - ./data/db:/app/db

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery_beat
    depends_on:
      - celery_worker
    volumes:
      - ./data/db:/app/db

  redis:
    image: "redis:latest"
