# Generated by Django 5.0 on 2023-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('vector', models.CharField(max_length=50)),
                ('nvd_links', models.TextField()),
                ('google_links', models.TextField()),
                ('cvss_two', models.FloatField(blank=True, null=True)),
                ('cvss_three', models.FloatField(blank=True, null=True)),
                ('cwe_id', models.CharField(max_length=10)),
                ('cwe_name', models.CharField(max_length=50)),
                ('cwe_link', models.URLField()),
                ('exploit_link', models.URLField()),
            ],
        ),
    ]
