# Generated by Django 5.0 on 2023-12-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvereport',
            old_name='vector',
            new_name='cvss_two_vector',
        ),
        migrations.AddField(
            model_name='cvereport',
            name='cvss_three_vector',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvereport',
            name='cwe_name',
            field=models.CharField(max_length=200),
        ),
    ]
