# Generated by Django 5.0 on 2023-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_report', '0002_rename_vector_cvereport_cvss_two_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cvereport',
            name='google_links',
        ),
        migrations.RemoveField(
            model_name='cvereport',
            name='nvd_links',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tags', models.ManyToManyField(to='cve_report.tag')),
            ],
        ),
        migrations.AddField(
            model_name='cvereport',
            name='google_links',
            field=models.ManyToManyField(related_name='google_links', to='cve_report.link'),
        ),
        migrations.AddField(
            model_name='cvereport',
            name='nvd_links',
            field=models.ManyToManyField(related_name='nvd_links', to='cve_report.link'),
        ),
    ]
